name: Sellsword
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37377
title: Sellsword - Seriously Unserious Heavy/Power Metal from Yorkshire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#210900'
    - '#f7cf87'
    - '#402400'
    - '#78572a'
    - '#b18b53'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
